version: '2.0'
services:
  mysql:
    restart: always
    build: ./mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    restart: always
    ports:
      - '3306:3306'
    volumes:
      - ./data/mysql:/var/lib/mysql
